name: Update submodules

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update submodules
        run: |
          git config --global user.email "fantasysa@gmail.com"
          git config --global user.name "Github action"
          echo `git submodule update --rebase --remote`
          echo `git commit -am "Update submodules. (by github action)"`
          git push
