name: Checkout submodules

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: git submodule
        run: |
          git config --global user.email "fantasysa@gmail.com"
          git config --global user.name "Github action"
          git submodule update --rebase --remote
          echo `git commit -am "Update submodules. (by github action)"`
          git push
