name: Checkout submodules

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
