name: Update submodules

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update submodules
        run: |
          git config --global user.email "fantasysa@gmail.com"
          git config --global user.name "Mark"
          git submodule update --recursive --remote --merge
          git diff
          git add .
          echo 'git commit -m "Update submodules. (by github action)"'
          git push
